version: "3.8"
services:
  main:
    build: ./main
    container_name: microfrontendadmin_container_main
    ports:
      - 3000:3000
    networks:
      - dev_network

  customer:
    build: ./customer
    container_name: microfrontendadmin_container_customer
    ports:
      - 3001:3001
    networks:
      - dev_network

  auth:
    build: ./auth
    container_name: microfrontendadmin_container_auth
    ports:
      - 3002:3002
    networks:
      - dev_network

  store:
    build: ./store
    container_name: microfrontendadmin_container_store
    ports:
      - 3030:3030
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
