version: "3.8"
services:
  main:
    build: ./main
    container_name: microfrontendadmin_container_main
    ports:
      - 4000:4000
    networks:
      - dev_network

  customer:
    build: ./customer
    container_name: microfrontendadmin_container_customer
    ports:
      - 4001:4001
    networks:
      - dev_network

  auth:
    build: ./auth
    container_name: microfrontendadmin_container_auth
    ports:
      - 4002:4002
    networks:
      - dev_network

  paymenthistory:
    build: ./paymenthistory
    container_name: microfrontendadmin_container_paymenthistory
    ports:
      - 4005:4005
    networks:
      - dev_network

  role:
    build: ./role
    container_name: microfrontendadmin_container_role
    ports:
      - 4006:4006
    networks:
      - dev_network

  settings:
    build: ./settings
    container_name: microfrontendadmin_container_settings
    ports:
      - 4007:4007
    networks:
      - dev_network

  subscription:
    build: ./subscription
    container_name: microfrontendadmin_container_subscription
    ports:
      - 4004:4004
    networks:
      - dev_network

  store:
    build: ./store
    container_name: microfrontendadmin_container_store
    ports:
      - 4030:4030
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
