apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendadmin-main-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontendadmin-main-service
  template:
    metadata:
      labels:
        app: frontendadmin-main-service
    spec:
      containers:
      - name: frontendadmin-main-service
        image: hordansodevops/reseller_admin_frontend_main:latest
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
        

