apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendadmin-paymenthistory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontendadmin-paymenthistory-service
  template:
    metadata:
      labels:
        app: frontendadmin-paymenthistory-service
    spec:
      containers:
      - name: frontendadmin-paymenthistory-service
        image: hordansodevops/reseller_admin_frontend_paymenthistory:latest
        ports:
        - containerPort: 4005
        imagePullPolicy: Always
