apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendadmin-store-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendadmin-store-service
  template:
    metadata:
      labels:
        app: frontendadmin-store-service
    spec:
      containers:
      - name: frontendadmin-store-service
        image: hordansodevops/reseller_admin_frontend_store:latest
        ports:
        - containerPort: 4030
        imagePullPolicy: Always
