apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendadmin-subscription-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontendadmin-subscription-service
  template:
    metadata:
      labels:
        app: frontendadmin-subscription-service
    spec:
      containers:
      - name: frontendadmin-subscription-service
        image: hordansodevops/reseller_admin_frontend_subscription:latest
        ports:
        - containerPort: 4004
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 4004
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 4004
          initialDelaySeconds: 5
          periodSeconds: 3
