apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminfrontend-vouchernotification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adminfrontend-vouchernotification-service
  template:
    metadata:
      labels:
        app: adminfrontend-vouchernotification-service
    spec:
      containers:
      - name: adminfrontend-vouchernotification-service
        image: hordansodevops/reseller_admin_frontend_vouchernotification:latest
        ports:
        - containerPort: 4003
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 4003
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 4003
          initialDelaySeconds: 5
          periodSeconds: 3