name: CI for Subscription Service

on:
    push:
        branches:
            - main
        paths:
            - "vouchernotification/**"
    workflow_dispatch: # Allow manual triggering

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      hordansodevops/reseller_admin_frontend_vouchernotification

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./vouchernotification
                  file: ./vouchernotification/Dockerfile
                  push: true
                  tags: >
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}_vouchernotification:${{ github.sha }},
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}_vouchernotification:latest
            - name: Set up kubectl
              uses: azure/setup-kubectl@v4
              with:
                  version: "v1.30.0"

            - name: Kubernetes set context
              uses: Azure/k8s-set-context@v3
              with:
                  method: kubeconfig
                  kubeconfig: ${{ secrets.KUBECONFIG }}

            - name: Deploy to Kubernetes
              uses: Azure/k8s-deploy@v3
              with:
                  action: deploy
                  strategy: basic
                  imagepullsecrets: |
                      ${{ secrets.REGISTRY_PULL_SECRET }}
                  manifests: |
                      k8s/vouchernotification-deployment.yaml
                      k8s/vouchernotification-service.yaml
                  images: |
                      hordansodevops/reseller_admin_frontend_vouchernotification:latest

            # Uncomment if you have a separate ingress deployment
            # - name: Deploy Ingress
            #   uses: Azure/k8s-deploy@v3
            #   with:
            #     action: deploy
            #     strategy: basic
            #     manifests: |
            #       k8s/ingress.yaml
